---
# tasks file for role_gpu_node

- name: Check OS version and family
  ansible.builtin.fail:
    msg: "This role can only be run against Ubuntu 20. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when: (ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version is version_compare('20', '!='))

- name: "Check OS version and family"
  ansible.builtin.debug:
    msg: "PASS | This role can only be executed on Ubuntu 20 operating systems, detected {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
  when: (ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version is version_compare('20', '=='))
# /etc/cloud/templates/hosts.debian.tmpl
# /etc/hosts
# install libtiff-dev ghostscript ghostscript cmake --yes
#
