---
# tasks file for role_gpu_node
- name: Check OS version and family
  ansible.builtin.fail:
    msg: "This role can only be run against Ubuntu 20. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when: (ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version is version_compare('20', '!='))

- name: "Check OS version and family"
  ansible.builtin.debug:
    msg: "PASS | This role can only be executed on Ubuntu 20 operating systems, detected {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
  when: (ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version is version_compare('20', '=='))

- name: "Change hosts.debian.tmpl file."
  ansible.builtin.blockinfile:
    path: /etc/cloud/templates/hosts.debian.tmpl
    insertafter: "127.0.0.1 localhost"
    block: |
      {% for name, ip in host_list.items() %}
        {% if name != ansible_hostname %}
      {{ ip }}   {{ name }}
        {% endif %}  
      {% endfor %}

- name: "Change /etc/hosts file."
  ansible.builtin.blockinfile:
    path: /etc/hosts
    insertafter: "127.0.0.1 localhost"
    block: |
      {% for name, ip in host_list.items() %}
        {% if name != ansible_hostname %}
      {{ ip }}   {{ name }}
        {% endif %}   
      {% endfor %}

- name: "Install neeeded packages."
  ansible.builtin.apt:
    name:
      - libtiff-dev
      - ghostscript
      - cmake
    state: present
  retries: 3

- name: "Remove unattended upgrades."
  ansible.builtin.apt:
    name: unattended-upgrades
    state: absent

- name: "Disable cloud-init network configuration."
  ansible.builtin.lineinfile:
    path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
    line: "network: {config: disabled}"
    state: present
    create: yes

- name: Remove usb0 device from netplan.
  ansible.builtin.blockinfile:
    path: /etc/netplan/50-cloud-init.yaml
    block: |
      usb0:
        match:
          macaddress: 00:00:00:00:00:00
        mtu: 1500
        set-name: usb0
    state: absent

- name: Apply netplan.
  ansible.builtin.shell:
    cmd: netplan apply

- name: Setup permissions for ssd cache.
  ansible.builtin.file:
    path: /ssd_cache
    state: directory
    owner: "{{ ssd_cache_owner }}"
    group: "{{ ssd_cache_group }}"
    mode: "0777"

- name: Disable hibernate.
  ansible.builtin.systemd:
    name: "{{ item }}"
    masked: yes
  with_items:
    - sleep.target
    - suspend.target
    - hibernate.target
    - hybrid-sleep.target
